In [1]:
from datascience import *
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

# Data Cleaning

In [10]:
gss = pd.read_csv('socio.csv')[:-1]
gss

,YEAR,REALINC ($),TVHOURS,POLHITOK,CLASS,HAPPY,VISIONS,ESP,DEJAVU,REGION,RACE,DEGREE,EDUC,CHILDS,SIBS,HRS1,REALRINC
0,1972,18951,Not applicable,Not applicable,Middle class,Not too happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,Bachelor,16,0,3,Not applicable,0.0
1,1972,24366,Not applicable,Not applicable,Middle class,Not too happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,Lt high school,10,5,4,Not applicable,0.0
2,1972,24366,Not applicable,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,High school,12,4,5,Not applicable,0.0
3,1972,30458,Not applicable,Not applicable,Middle class,Not too happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,Bachelor,17,0,5,Not applicable,0.0
4,1972,50763,Not applicable,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,High school,12,2,2,Not applicable,0.0
5,1972,43994,Not applicable,Not applicable,Middle class,Pretty happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,High school,14,0,1,Not applicable,0.0
6,1972,37226,Not applicable,Not applicable,Middle class,Not too happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,High school,13,2,7,Not applicable,0.0
7,1972,13537,Not applicable,Not applicable,Working class,Not too happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,Bachelor,16,0,1,Not applicable,0.0
8,1972,2707,Not applicable,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,W. sou. central,Black,High school,12,2,2,Not applicable,0.0
9,1972,18951,Not applicable,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,W. sou. central,Black,High school,12,4,7,Not applicable,0.0
10,1972,13537,Not applicable,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,W. sou. central,Black,High school,13,1,7,Not applicable,0.0
11,1972,13537,Not applicable,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,W. sou. central,Black,Lt high school,6,5,6,Not applicable,0.0
12,1972,13537,Not applicable,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,W. sou. central,Black,Lt high school,9,1,2,Not applicable,0.0
13,1972,13537,Not applicable,Not applicable,Working class,Not too happy,Not applicable,Not applicable,Not applicable,W. sou. central,Black,Lt high school,8,2,2,Not applicable,0.0
14,1972,18951,Not applicable,Not applicable,Middle class,Very happy,Not applicable,Not applicable,Not applicable,W. sou. central,Black,Lt high school,9,5,0,Not applicable,0.0
15,1972,13537,Not applicable,Not applicable,Working class,Not too happy,Not applicable,Not applicable,Not applicable,W. sou. central,Black,High school,14,2,7,Not applicable,0.0
16,1972,24366,Not applicable,Not applicable,Working class,Very happy,Not applicable,Not applicable,Not applicable,W. sou. central,White,High school,14,2,0,Not applicable,0.0
17,1972,18951,Not applicable,Not applicable,Middle class,Very happy,Not applicable,Not applicable,Not applicable,W. sou. central,White,Lt high school,8,3,2,Not applicable,0.0
18,1972,43994,Not applicable,Not applicable,Middle class,Very happy,Not applicable,Not applicable,Not applicable,W. sou. central,White,Bachelor,17,3,2,Not applicable,0.0
19,1972,50763,Not applicable,Not applicable,Middle class,Very happy,Not applicable,Not applicable,Not applicable,W. sou. central,White,High school,14,0,7,Not applicable,0.0
20,1972,37226,Not applicable,Not applicable,Middle class,Very happy,Not applicable,Not applicable,Not applicable,W. sou. central,White,High school,12,2,2,Not applicable,0.0
21,1972,60915,Not applicable,Not applicable,Upper class,Very happy,Not applicable,Not applicable,Not applicable,W. sou. central,White,High school,11,2,1,Not applicable,0.0
22,1972,13537,Not applicable,Not applicable,Working class,Very happy,Not applicable,Not applicable,Not applicable,W. sou. central,White,High school,13,0,1,Not applicable,0.0
23,1972,18951,Not applicable,Not applicable,Working class,Very happy,Not applicable,Not applicable,Not applicable,W. sou. central,White,High school,12,1,7,Not applicable,0.0
24,1972,30458,Not applicable,Not applicable,Middle class,Pretty happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,Bachelor,16,0,2,Not applicable,0.0
25,1972,30458,Not applicable,Not applicable,Working class,Very happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,High school,12,2,7,Not applicable,0.0
26,1972,30458,Not applicable,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,High school,12,2,5,Not applicable,0.0
27,1972,30458,Not applicable,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,High school,12,2,4,Not applicable,0.0
28,1972,0,Not applicable,Not applicable,Middle class,Pretty happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,High school,12,0,2,Not applicable,0.0
29,1972,30458,Not applicable,Not applicable,Middle class,Pretty happy,Not applicable,Not applicable,Not applicable,E. nor. central,White,Lt high school,9,2,4,Not applicable,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64785,2018,0,4,No,Lower class,Pretty happy,Not applicable,Not applicable,Not applicable,South atlantic,Black,High school,10,3,7,30,0.0
64786,2018,20430,4,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,South atlantic,Black,High school,12,2,10,Not applicable,0.0
64787,2018,37455,Not applicable,Yes,Middle class,Pretty happy,Not applicable,Not applicable,Not applicable,South atlantic,White,Bachelor,15,2,3,46,37455.0
64788,2018,45400,0,Yes,Middle class,Pretty happy,Not applicable,Not applicable,Not applicable,South atlantic,White,Junior college,14,1,1,40,30645.0
64789,2018,30645,0,Yes,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,Bachelor,16,2,1,Not applicable,0.0
64790,2018,0,5,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,High school,12,3,5,Not applicable,2951.0
64791,2018,45400,1,Not applicable,Middle class,Very happy,Not applicable,Not applicable,Not applicable,New england,White,Bachelor,16,3,3,55,2951.0
64792,2018,37455,Not applicable,Yes,Middle class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,High school,12,4,3,27,37455.0
64793,2018,908,2,Yes,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,Bachelor,16,0,2,Not applicable,908.0
64794,2018,45400,Not applicable,Yes,Middle class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,Graduate,17,3,3,Not applicable,0.0
64795,2018,24970,2,Yes,Working class,Not too happy,Not applicable,Not applicable,Not applicable,New england,White,High school,14,2,1,Not applicable,0.0
64796,2018,54480,1,Yes,Middle class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,Junior college,14,2,3,28,24970.0
64797,2018,9647.5,3,No,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,High school,12,0,2,Not applicable,0.0
64798,2018,119879.4173,Not applicable,Yes,Middle class,Very happy,Not applicable,Not applicable,Not applicable,New england,White,Bachelor,17,2,1,Not applicable,0.0
64799,2018,72640,2,Not applicable,Middle class,Very happy,Not applicable,Not applicable,Not applicable,New england,White,Graduate,20,2,3,Not applicable,0.0
64800,2018,17025,Not applicable,Yes,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,Graduate,18,5,1,Not applicable,0.0
64801,2018,45400,2,Not applicable,Middle class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,Graduate,18,0,7,37,17025.0
64802,2018,17025,2,Yes,Working class,Not too happy,Not applicable,Not applicable,Not applicable,New england,White,Bachelor,16,0,1,55,4086.0
64803,2018,0,Not applicable,Yes,Middle class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,High school,12,4,5,Not applicable,0.0
64804,2018,8512.5,Not applicable,Yes,Working class,Not too happy,Not applicable,Not applicable,Not applicable,New england,White,High school,12,3,2,Not applicable,0.0
64805,2018,24970,1,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,High school,14,0,1,60,14755.0
64806,2018,0,2,Yes,Don't know,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,Lt high school,8,2,6,Not applicable,0.0
64807,2018,4086,5,Not applicable,Lower class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,High school,14,2,4,Not applicable,0.0
64808,2018,7377.5,Not applicable,Yes,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,High school,12,0,3,Not applicable,0.0
64809,2018,0,2,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,High school,12,2,9,36,0.0
64810,2018,14755,6,Not applicable,Working class,Pretty happy,Not applicable,Not applicable,Not applicable,New england,White,High school,12,4,9,36,7377.5
64811,2018,45400,Not applicable,Yes,Middle class,Very happy,Not applicable,Not applicable,Not applicable,New england,White,High school,12,3,3,Not applicable,1589.0
64812,2018,24970,1,Yes,Middle class,Very happy,Not applicable,Not applicable,Not applicable,New england,White,High school,16,2,1,Not applicable,0.0
64813,2018,0,1,Not applicable,Working class,Very happy,Not applicable,Not applicable,Not applicable,New england,White,High school,12,6,10,Not applicable,0.0
64814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# check the data types of each variable
gss.dtypes

YEAR            object
REALINC ($)     object
TVHOURS         object
POLHITOK        object
CLASS           object
HAPPY           object
VISIONS         object
ESP             object
DEJAVU          object
REGION          object
RACE            object
DEGREE          object
EDUC            object
CHILDS          object
SIBS            object
HRS1            object
REALRINC       float64
dtype: object

In [27]:
# numerical variables are data type 'object', not int & change 'not applicable' to -1
# we need to convert it to do aggregate functions

gss['YEAR'] = gss['YEAR'].fillna(-1)
gss['REALINC ($)'] = pd.to_numeric(gss['REALINC ($)'], errors = 'coerce').fillna(np.nan)
gss['TVHOURS'] = pd.to_numeric(gss['TVHOURS'], errors = 'coerce').fillna(np.nan)
gss['EDUC'] = pd.to_numeric(gss['EDUC'], errors = 'coerce').fillna(np.nan)
gss['CHILDS'] = pd.to_numeric(gss['CHILDS'], errors = 'coerce').fillna(np.nan)
gss['SIBS'] = pd.to_numeric(gss['SIBS'], errors = 'coerce').fillna(np.nan)
gss['HRS1'] = pd.to_numeric(gss['HRS1'], errors = 'coerce').fillna(np.nan)
gss['REALRINC'] = pd.to_numeric(gss['REALRINC'], errors = 'coerce').fillna(np.nan)
gss.drop(64814, inplace = True)

gss.dtypes
gss

KeyError: '[64814] not found in axis'

In [13]:
gss.to_csv('cleaned_data.csv')

In [14]:
def lineplot(x, y, data):
    sns.lineplot(x = x, y = y, data = data)
    plt.xlim(1970, 2018)

In [15]:
def distplot(column, data, color):
    plt.figure(figsize=(8,4))
    sns.distplot(data[column], color = color)

In [16]:
def mode_distplot(column, data, color): 
    plt.figure(figsize=(8,4))
    sns.distplot(data[column], color = color, kde= False, rug = False)

In [17]:
def marker(value):
    plt.axvline(value, color = 'black', linewidth = 1.3)

In [18]:
#marker in diff color (for comparisons)
def second_marker(value):
    plt.axvline(value, color = 'yellow', linewidth = 1.3)

In [19]:
def mean(data, column):
    return np.mean(data[column])

In [20]:
def show_greater_than(data, column, value):
    return data[data[column] > value]

In [21]:
def show_less_than(data, column, value):
    return data[data[column] < value]

In [22]:
def show_greater_equal(data, column, value):
    return data[data[column] >= value]